### PR TITLE
Custom drop on PyBufferWrapper

### PR DESCRIPTION
**Pull request by kylebarron**
Closes https://github.com/kylebarron/arro3/issues/230

This is a bit of a hacky implementation, but I'm not sure of another way to do this.

@3ok This seems to work for me, would you be interested in testing this branch?

### CODE REVIEW

**Comment by kylebarron** [comment]
I don't know of a great way to test this on CI, and I'd like to get this into a bug fix ASAP with #232, so I'll merge this. But open to more feedback on the best way to do this!

**Comment by 3ok** [comment]
Thank you for looking into it. I will take a look at it later today. 🙂

**Comment by 3ok** [comment]
Hi @kylebarron I have built against the latest changes in `main` and indeed I do not notice the issue anymore. 🥳 

I'm not sure if that would work but I guess one way to test this is to have it run in a separate subprocess?

**Comment by kylebarron** [comment]
If you're able to put up a PR with a test, that would be greatly appreciated!

**Pull request merged**
